#!/bin/bash

setTemplate=false
setStatic=false

args()
{
	if [[ $1 == '--templates' ]] || [[ $1 == '-t' ]]
	then
		echo "Copie des templates à l'emplacement $2"
		setTemplate=true
	elif [[ $1 == '--static' ]] || [[ $1 == '-s' ]]
	then
		echo "Copie des statics à l'emplacement $2"
		setStatic=true
	fi
}


if [[ -n $1 ]]
then
	if [[ -n $2 ]]
	then
		args $1 $2
	else
		echo 'Erreur: Argument manquant'
	fi
fi
if [[ -n $3 ]]
then
	if [[ -n $4 ]]
	then
		if [[ $3 == $1 ]]
		then
			echo 'Attention, vous avez deux arguments identiques'
		else
			args $3 $4
		fi
	fi
fi

if [[ $setTemplate == true ]]
then
	echo mabite
fi

if [[ $setStatic == true ]]
then
	echo yay
fi
